"""MyAI Prompts — system prompts for all agents."""

from .master import MASTER_SYSTEM, MASTER_CLASSIFY
from .planner import PLANNER_SYSTEM, PLANNER_CREATE
from .transport import TRANSPORT_SYSTEM, TRANSPORT_NORMALIZE
from .analytics import ANALYTICS_SYSTEM, ANALYTICS_CALCULATE
from .reviewer import REVIEWER_SYSTEM, REVIEWER_VERIFY

__all__ = [
    "MASTER_SYSTEM", "MASTER_CLASSIFY",
    "PLANNER_SYSTEM", "PLANNER_CREATE",
    "TRANSPORT_SYSTEM", "TRANSPORT_NORMALIZE",
    "ANALYTICS_SYSTEM", "ANALYTICS_CALCULATE",
    "REVIEWER_SYSTEM", "REVIEWER_VERIFY",
]
